{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2009-0544"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "Buffer overflow in the PyCrypto ARC2 module 2.0.1 allows remote attackers to cause a denial of service and possibly execute arbitrary code via a large ARC2 key length."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-119"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=d1c4875e1f220652fe7ff8358f56dee3b2aba31b",
					"url": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=d1c4875e1f220652fe7ff8358f56dee3b2aba31b"
				},
				{
					"name": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=d1c4875e1f220652fe7ff8358f56dee3b2aba31b",
					"url": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=d1c4875e1f220652fe7ff8358f56dee3b2aba31b"
				},
				{
					"name": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=fd73731dfad451a81056fbb01e09aa78ab82eb5d",
					"url": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=fd73731dfad451a81056fbb01e09aa78ab82eb5d"
				},
				{
					"name": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=fd73731dfad451a81056fbb01e09aa78ab82eb5d",
					"url": "http://gitweb2.dlitz.net/?p=crypto/pycrypto-2.x.git%3Ba=commitdiff%3Bh=fd73731dfad451a81056fbb01e09aa78ab82eb5d"
				},
				{
					"name": "SUSE-SR:2009:010",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2009-05/msg00000.html"
				},
				{
					"name": "SUSE-SR:2009:010",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2009-05/msg00000.html"
				},
				{
					"name": "34199",
					"url": "http://secunia.com/advisories/34199"
				},
				{
					"name": "34199",
					"url": "http://secunia.com/advisories/34199"
				},
				{
					"name": "35065",
					"url": "http://secunia.com/advisories/35065"
				},
				{
					"name": "35065",
					"url": "http://secunia.com/advisories/35065"
				},
				{
					"name": "GLSA-200903-11",
					"url": "http://www.gentoo.org/security/en/glsa/glsa-200903-11.xml"
				},
				{
					"name": "GLSA-200903-11",
					"url": "http://www.gentoo.org/security/en/glsa/glsa-200903-11.xml"
				},
				{
					"name": "MDVSA-2009:049",
					"url": "http://www.mandriva.com/security/advisories?name=MDVSA-2009:049"
				},
				{
					"name": "MDVSA-2009:049",
					"url": "http://www.mandriva.com/security/advisories?name=MDVSA-2009:049"
				},
				{
					"name": "MDVSA-2009:050",
					"url": "http://www.mandriva.com/security/advisories?name=MDVSA-2009:050"
				},
				{
					"name": "MDVSA-2009:050",
					"url": "http://www.mandriva.com/security/advisories?name=MDVSA-2009:050"
				},
				{
					"name": "[oss-security] 20090207 CVE Request: pycrypto",
					"url": "http://www.openwall.com/lists/oss-security/2009/02/07/1"
				},
				{
					"name": "[oss-security] 20090207 CVE Request: pycrypto",
					"url": "http://www.openwall.com/lists/oss-security/2009/02/07/1"
				},
				{
					"name": "[oss-security] 20090212 Re: CVE Request: pycrypto",
					"url": "http://www.openwall.com/lists/oss-security/2009/02/12/5"
				},
				{
					"name": "[oss-security] 20090212 Re: CVE Request: pycrypto",
					"url": "http://www.openwall.com/lists/oss-security/2009/02/12/5"
				},
				{
					"name": "33674",
					"tags": [
						"Exploit"
					],
					"url": "http://www.securityfocus.com/bid/33674"
				},
				{
					"name": "33674",
					"tags": [
						"Exploit"
					],
					"url": "http://www.securityfocus.com/bid/33674"
				},
				{
					"name": "pycrypto-arc2module-bo(48617)",
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/48617"
				},
				{
					"name": "pycrypto-arc2module-bo(48617)",
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/48617"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "COMPLETE",
				"baseScore": 10,
				"confidentialityImpact": "COMPLETE",
				"integrityImpact": "COMPLETE",
				"vectorString": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 10,
			"severity": "HIGH"
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:pycrypto:arc2:2.0.1:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T01:00Z",
	"publishedDate": "2009-02-12T17:30Z"
}
