{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cna@python.org",
			"ID": "CVE-2024-3219"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://github.com/python/cpython/pull/122134",
					"url": "https://github.com/python/cpython/pull/122134"
				},
				{
					"name": "https://github.com/python/cpython/issues/122133",
					"url": "https://github.com/python/cpython/issues/122133"
				},
				{
					"name": "https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/",
					"url": "https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/"
				},
				{
					"name": "http://www.openwall.com/lists/oss-security/2024/07/29/3",
					"url": "http://www.openwall.com/lists/oss-security/2024/07/29/3"
				}
			]
		}
	},
	"impact": {},
	"configurations": {
		"CVE_data_version": "4.0"
	},
	"lastModifiedDate": "2024-07-30T01:15Z",
	"publishedDate": "2024-07-29T22:15Z"
}
