{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "secalert@redhat.com",
			"ID": "CVE-2024-0229"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "An out-of-bounds memory access flaw was found in the X.Org server. This issue can be triggered when a device frozen by a sync grab is reattached to a different master device. This issue may lead to an application crash, local privilege escalation (if the server runs with extended privileges), or remote code execution in SSH X11 forwarding environments."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-788"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "RHSA-2024:0320",
					"url": "https://access.redhat.com/errata/RHSA-2024:0320"
				},
				{
					"name": "RHSA-2024:0557",
					"url": "https://access.redhat.com/errata/RHSA-2024:0557"
				},
				{
					"name": "RHSA-2024:0558",
					"url": "https://access.redhat.com/errata/RHSA-2024:0558"
				},
				{
					"name": "RHSA-2024:0597",
					"url": "https://access.redhat.com/errata/RHSA-2024:0597"
				},
				{
					"name": "RHSA-2024:0607",
					"url": "https://access.redhat.com/errata/RHSA-2024:0607"
				},
				{
					"name": "RHSA-2024:0614",
					"url": "https://access.redhat.com/errata/RHSA-2024:0614"
				},
				{
					"name": "RHSA-2024:0617",
					"url": "https://access.redhat.com/errata/RHSA-2024:0617"
				},
				{
					"name": "RHSA-2024:0621",
					"url": "https://access.redhat.com/errata/RHSA-2024:0621"
				},
				{
					"name": "RHSA-2024:0626",
					"url": "https://access.redhat.com/errata/RHSA-2024:0626"
				},
				{
					"name": "RHSA-2024:0629",
					"url": "https://access.redhat.com/errata/RHSA-2024:0629"
				},
				{
					"name": "https://access.redhat.com/security/cve/CVE-2024-0229",
					"url": "https://access.redhat.com/security/cve/CVE-2024-0229"
				},
				{
					"name": "RHBZ#2256690",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2256690"
				}
			]
		}
	},
	"impact": {},
	"configurations": {
		"CVE_data_version": "4.0"
	},
	"lastModifiedDate": "2024-02-09T07:16Z",
	"publishedDate": "2024-02-09T07:16Z"
}
