{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "psirt@us.ibm.com",
			"ID": "CVE-2024-31904"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "IBM App Connect Enterprise 11.0.0.1 through 11.0.0.25 and 12.0.1.0 through 12.0.12.0 integration nodes could allow an authenticated user to cause a denial of service due to an uncaught exception.  IBM X-Force ID:  289647."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-248"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://www.ibm.com/support/pages/node/7154607",
					"url": "https://www.ibm.com/support/pages/node/7154607"
				},
				{
					"name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/289647",
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/289647"
				}
			]
		}
	},
	"impact": {},
	"configurations": {
		"CVE_data_version": "4.0"
	},
	"lastModifiedDate": "2024-05-22T19:15Z",
	"publishedDate": "2024-05-22T19:15Z"
}
