{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "secalert@redhat.com",
			"ID": "CVE-2010-2073"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "auth_db_config.py in Pyftpd 0.8.4 contains hard-coded usernames and passwords for the (1) test, (2) user, and (3) roxon accounts, which allows remote attackers to read arbitrary files from the FTP server."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-798"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=585776",
					"tags": [
						"Mailing List",
						"Patch"
					],
					"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=585776"
				},
				{
					"name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=585776",
					"tags": [
						"Mailing List",
						"Patch"
					],
					"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=585776"
				},
				{
					"name": "[oss-security] 20100613 CVE request - pyftpd default username and password vulnerability",
					"tags": [
						"Mailing List"
					],
					"url": "http://www.openwall.com/lists/oss-security/2010/06/13/2"
				},
				{
					"name": "[oss-security] 20100613 CVE request - pyftpd default username and password vulnerability",
					"tags": [
						"Mailing List"
					],
					"url": "http://www.openwall.com/lists/oss-security/2010/06/13/2"
				},
				{
					"name": "40839",
					"tags": [
						"Broken Link",
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "http://www.securityfocus.com/bid/40839"
				},
				{
					"name": "40839",
					"tags": [
						"Broken Link",
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "http://www.securityfocus.com/bid/40839"
				},
				{
					"name": "pyftpd-default-account(59431)",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/59431"
				},
				{
					"name": "pyftpd-default-account(59431)",
					"tags": [
						"Third Party Advisory",
						"VDB Entry"
					],
					"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/59431"
				}
			]
		}
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"accessComplexity": "LOW",
				"accessVector": "NETWORK",
				"authentication": "NONE",
				"availabilityImpact": "NONE",
				"baseScore": 5,
				"confidentialityImpact": "PARTIAL",
				"integrityImpact": "NONE",
				"vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
				"version": "2.0"
			},
			"exploitabilityScore": 10,
			"impactScore": 2.9,
			"severity": "MEDIUM"
		},
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "NONE",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "HIGH",
				"integrityImpact": "NONE",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:debian:pyftpd:0.8.4:*:*:*:*:*:*:*",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T01:15Z",
	"publishedDate": "2010-06-16T20:30Z"
}
