{
	"cve": {
		"CVE_data_meta": {
			"ASSIGNER": "cve@mitre.org",
			"ID": "CVE-2022-42969"
		},
		"data_format": "MITRE",
		"data_type": "CVE",
		"data_version": "4.0",
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled. Note: This has been disputed by multiple third parties as not being reproduceable and they argue this is not a valid vulnerability."
				}
			]
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-1333"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"name": "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316",
					"tags": [
						"Product"
					],
					"url": "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"
				},
				{
					"name": "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316",
					"tags": [
						"Product"
					],
					"url": "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"
				},
				{
					"name": "https://github.com/pytest-dev/py/issues/287",
					"tags": [
						"Exploit",
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://github.com/pytest-dev/py/issues/287"
				},
				{
					"name": "https://github.com/pytest-dev/py/issues/287",
					"tags": [
						"Exploit",
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://github.com/pytest-dev/py/issues/287"
				},
				{
					"name": "https://news.ycombinator.com/item?id=34163710",
					"tags": [
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://news.ycombinator.com/item?id=34163710"
				},
				{
					"name": "https://news.ycombinator.com/item?id=34163710",
					"tags": [
						"Issue Tracking",
						"Third Party Advisory"
					],
					"url": "https://news.ycombinator.com/item?id=34163710"
				},
				{
					"name": "https://pypi.org/project/py",
					"tags": [
						"Product"
					],
					"url": "https://pypi.org/project/py"
				},
				{
					"name": "https://pypi.org/project/py",
					"tags": [
						"Product"
					],
					"url": "https://pypi.org/project/py"
				}
			]
		}
	},
	"impact": {
		"baseMetricV3": {
			"cvssV3": {
				"attackComplexity": "LOW",
				"attackVector": "NETWORK",
				"availabilityImpact": "HIGH",
				"baseScore": 7.5,
				"baseSeverity": "HIGH",
				"confidentialityImpact": "NONE",
				"integrityImpact": "NONE",
				"privilegesRequired": "NONE",
				"scope": "UNCHANGED",
				"userInteraction": "NONE",
				"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
				"version": "3.1"
			},
			"exploitabilityScore": 3.9,
			"impactScore": 3.6
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"cpe_match": [
					{
						"cpe23Uri": "cpe:2.3:a:pytest:py:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "1.11.0",
						"vulnerable": true
					}
				],
				"operator": "OR"
			}
		]
	},
	"lastModifiedDate": "2024-11-21T07:25Z",
	"publishedDate": "2022-10-16T06:15Z"
}
